### ISSUE TITLE
[ERR]Could not get restli body request

### ISSUE THREAD

**Issue by SaschaAC** [cristminix/lil#2]
Hi,

i got this error.

Best Sascha

[LOG]Human start browsing this url:https://www.linkedin.com/learning
[LOG]Resp Code 200
[LOG]Write file ..\storage\browser_cache\linkedin_learning_homepage-1.html success
[INFO]You are loged in
[LOG]Human start browsing this url:https://www.linkedin.com/learning/windows-10-lernen
[LOG]Resp Code 200
[LOG]Write file ..\storage\browser_cache\ll-learning-windows-10-lernen.xml success
[ERR]Could not get restli body request
Traceback (most recent call last):
  File "C:\lil\lil-main\lil\bin\lil.py", line 70, in <module>
    main()
  File "C:\lil\lil-main\lil\bin\lil.py", line 59, in main
    fetch(args)
  File "C:\lil\lil-main\lil\bin\fetch.py", line 38, in fetch
    course = api_course.getCourseInfo(course_slug,refresh=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lil\lil-main\lil\api\course_api.py", line 158, in getCourseInfo
    course = self.fetchCourseInfo(course_slug,refresh=refresh)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lil\lil-main\lil\api\course_api.py", line 222, in fetchCourseInfo
    course = getCourseInfo(xml_doc)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\lil\lil-main\lil\api\course_fn.py", line 233, in getCourseInfo
    p,course_urn = getCourseXmlParentElement(doc)
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
(.venv)

**Comment by jeg-labs** [comment]
Same for me

[LOG]Human start browsing this url:https://www.linkedin.com/learning
[LOG]Resp Code 200
[LOG]Write file ..\storage\browser_cache\linkedin_learning_homepage-1.html success
[INFO]You are loged in
[LOG]Human start browsing this url:https://www.linkedin.com/learning/creating-screen-capture-training
[LOG]Resp Code 200
[LOG]Write file ..\storage\browser_cache\ll-learning-creating-screen-capture-training.xml success
[ERR]Could not get restli body request
Traceback (most recent call last):
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\bin\lil.py", line 70, in <module>
    main()
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\bin\lil.py", line 59, in main
    fetch(args)
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\bin\fetch.py", line 38, in fetch
    course = api_course.getCourseInfo(course_slug,refresh=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\api\course_api.py", line 158, in getCourseInfo
    course = self.fetchCourseInfo(course_slug,refresh=refresh)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\api\course_api.py", line 222, in fetchCourseInfo
    course = getCourseInfo(xml_doc)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eduar\EDQUAKE\General Stuff - Documents\projects\linkedin transcripts\resources downloader in python\from github\lil\api\course_fn.py", line 233, in getCourseInfo
    p,course_urn = getCourseXmlParentElement(doc)
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
